"""initial migration

Revision ID: 15def7dd2870
Revises: 26b53d08fba8
Create Date: 2015-04-10 20:25:31.106000

"""

# revision identifiers, used by Alembic.
revision = '15def7dd2870'
down_revision = '26b53d08fba8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
