"""empty message

Revision ID: 1fecc308eebf
Revises: None
Create Date: 2015-04-03 15:46:07.154000

"""

# revision identifiers, used by Alembic.
revision = '1fecc308eebf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table(u'tracking')
    op.create_table(u'track',
        sa.Column(u'id', sa.Integer, nullable=False),
        sa.Column(u'name', sa.String, nullable=True),
        sa.Column(u'length', sa.Integer, nullable=True),
        sa.Column(u'day', sa.Integer, nullable=True),
        sa.Column(u'level', sa.String, nullable=True),
        sa.Column(u'text', sa.String, nullable=True),
        sa.Column(u'route', sa.String, nullable=True),
        sa.Column(u'img', sa.String, nullable=True),
        sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'roles',
        sa.Column(u'id', sa.Integer, nullable=False, primary_key=True),
        sa.Column(u'role', sa.SmallInteger, nullable=True)
    )
    op.create_table(
        'users', 
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('email', sa.String(length=64), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('remember_me', sa.Boolean(), nullable=True),      
        sa.Column('username', sa.String(length=64), nullable=True),      
        sa.Column('role_id', sa.Integer, nullable=True)      
    )
    op.create_index(u'ix_users_username', 'users', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    pass
