"""empty message

Revision ID: 1fecc308eebf
Revises: None
Create Date: 2015-04-03 15:46:07.154000

"""

# revision identifiers, used by Alembic.
revision = '1fecc308eebf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'tracking')
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('remember_me', sa.Boolean(), nullable=True))
    op.drop_index(u'ix_users_username', table_name='users')
    op.create_index(u'ix_users_username', 'users', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_users_username', table_name='users')
    op.create_index(u'ix_users_username', 'users', [u'username'], unique=1)
    op.drop_column('users', 'remember_me')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.create_table(u'tracking',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'tracking_name', sa.VARCHAR(), nullable=True),
    sa.Column(u'tracking_length', sa.INTEGER(), nullable=True),
    sa.Column(u'tracking_day', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
