"""empty message

Revision ID: 26b53d08fba8
Revises: 1fecc308eebf
Create Date: 2015-04-05 11:04:14.393000

"""

# revision identifiers, used by Alembic.
revision = '26b53d08fba8'
down_revision = '1fecc308eebf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'password', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
